# title: Free Landing Page HTML Template  # Name of the site
author:
  name: Michael Kündig
# metadata:
#     description: 'Land.io is a carefully crafted landing page UI kit and landing page template built on Bootstrap 4, designed by Peter Finlan and developed by Taty Grassini.'

# TopBar
logo:
  icon: logo
  text: Land.io
  url:

# User Panel
userlinks:
    - text: Sample link
      url: "#"
    - text: Another Sample link
      url: "#"

# Header customization
header:
  title: Kündig Schleifmittel
  # description: asdadsf
  buttons:
    - text: "Some Button"
      url: "http://tympanus.net/codrops/?p=19439"
      icon: "sketch"
    - text: "Another Button"
      url: "https://google.com"
      icon: "sketch"

# Footer customization
footer:
  links:
    - text: Terms &amp; Conditions
      url: "#"
    - text: Legals
      url: "#"
